import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Navbar from 'components/shared/navbar';
import Student from 'components/student/student';
import { getClassData } from 'utils/services/rest';

export default function Home({ list }) {
  return (
    <>
      <Head>
        <title>Class Attendance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {list.message.map((el) => {
        return (
          <Student
            name={el.name}
            email={el.email}
            status={el.attandance.status}
            regNo={el.usn}
            details={el.section}
            facultyName={el.counselor_name}
            facultyEmail={el.counselor_email}
          />
        );
      })}
    </>
  );
}

export async function getStaticProps() {
  const list = await getClassData();
  //   console.log(res);
  //   const list = await res.json();

  return {
    props: {
      list,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 10, // In seconds
  };
}
