import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Navbar from 'components/shared/navbar';
import Student from 'components/student/student';
import { getClassData } from 'utils/services/rest';
import { useState } from 'react';

export default function Home({ list }) {
  const [studentList, setStudentList] = useState(list.message);

  const StudentItems = ({ el }) => {
    const [status, setStatus] = useState(el.attandance.status);
    return (
      <Student
        key={el.regNo}
        list={studentList}
        name={el.name}
        email={el.email}
        status={status}
        regNo={el.usn}
        details={el.section}
        facultyName={el.counselor_name}
        facultyEmail={el.counselor_email}
        changeStatus={setStatus}
      />
    );
  };
  return (
    <>
      <Head>
        <title>Class Attendance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {list.message.map((el, i) => {
        return <StudentItems el={el} key={i} />;
      })}
      <div className="flex justify-center">
        <button
          className="px-10 py-5 bg-blue-800 text-white text-xl font-bold rounded-full"
          onClick={() => {
            console.log(list);
          }}
        >
          Update Attendance
        </button>
      </div>
    </>
  );
}

export async function getStaticProps() {
  const list = await getClassData();

  return {
    props: {
      list,
    },
  };
}
